replicaCount: 1

image:
  repository: look0608/devops-admin-frontend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-hub

service:
  type: NodePort
  port: 80

timezone: Asia/Shanghai

nacos:
  addr: "nacos.middleware:8848"
  namespace: ""
  group: "DEFAULT_GROUP"

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m

ingress:
  enabled: true
  className: traefik
  host: devops.192.168.86.9.nip.io
  path: /
  annotations: {}
  tls: []