apiVersion: v1
kind: Pod
metadata:
  name: mysql-tool
  namespace: middleware
spec:
  restartPolicy: Never
  containers:
  - name: mysql-tool
    image: alpine:3.19
    command:
      - sh
      - -c
      - |
        apk add --no-cache mariadb-client >/dev/null 2>&1
        echo 'ALTER USER "root"@"%" IDENTIFIED WITH mysql_native_password BY "Admin@123"; FLUSH PRIVILEGES; CREATE DATABASE IF NOT EXISTS xxl_job DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;' | mysql -h middleware-mysql -u root -pAdmin@123
        echo "Done"