apiVersion: v1
kind: Pod
metadata:
  name: mysql-tool
  namespace: middleware
spec:
  restartPolicy: Never
  containers:
  - name: mysql-tool
    image: mysql:8.0
    command:
      - bash
      - -c
      - |
        mysql -h middleware-mysql -u root --password=Admin@123 --default-auth=mysql_native_password -e 'ALTER USER "root"@"%" IDENTIFIED WITH mysql_native_password BY "Admin@123"; FLUSH PRIVILEGES; CREATE DATABASE IF NOT EXISTS xxl_job DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
        echo "DB Init Done"