replicaCount: 1

image:
  repository: corentinth/it-tools
  tag: 2023.11.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 200m