apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy.fullname" . }}
  labels:
    app: {{ include "proxy.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "proxy.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: PROXY_PORT
              value: "8080"
            - name: PROXY_ROUTES
              value: "{{ .Values.proxyRoutes }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}