{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harness-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: harness-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.adminPassword }}
{{- end }}
