{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: harness-secret
type: Opaque
stringData:
  admin-password: {{ .Values.env.GITNESS_PRINCIPAL_ADMIN_PASSWORD | quote }}
{{- end }}
