replicaCount: 1

image:
  repository: look0608/devops-admin-proxy
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-hub

service:
  type: ClusterIP
  port: 8080

timezone: Asia/Shanghai

# Route format: path->target,path->target
proxyRoutes: ""
# Example: /user/tool/ittool->http://it-tools:80

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m