replicaCount: 1

image:
  repository: rabbitmq
  tag: 3.13.7-management-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    amqp: 5672
    management: 15672

user: middleware
password: RabbitMQ2026!

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m