replicaCount: 1

image:
  repository: nacos/nacos-server
  tag: v3.1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    client: 8848
    rpc: 9848
    raft: 9849

mode: standalone

db:
  host: middleware-mysql
  port: 3306
  name: nacos
  user: nacos
  password: NacosDB2026!

auth:
  token: "TkFDT1NfQVVUSF9UT0tFTl82NEJZVEVTX0JBU0U2NF9TRUNSRVRfS0VZXzIwMjY="
  identityKey: "nacosIdentityKey"
  identityValue: "nacosIdentityValue2026"

persistence:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 768Mi
    cpu: 500m