{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres_password: {{ .Values.adminPassword | quote }}
  outline-password: {{ (index .Values.databases 0).password | quote }}
  litellm-password: {{ (index .Values.databases 1).password | quote }}
{{- end }}
