# Outline Wiki Configuration
replicaCount: 1

image:
  repository: docker.getoutline.com/outlinewiki/outline
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: outline.local
  tls: false

# Database - external (from backup restore)
postgresql:
  enabled: false
  external:
    host: outline-db-postgresql
    port: 5432
    database: outline
    user: outline
    password: OutlineDB2026!

redis:
  enabled: false
  external:
    host: outline-redis-master
    port: 6379
    password: ""

minio:
  enabled: false
  external:
    endpoint: outline-minio:9000
    accessKey: outline
    secretKey: OutlineMinio2026!
    bucket: outline

# Outline env vars
env:
  SECRET_KEY: "bac3c713a283273fd1764c81efc242721bbc228fd9f78c4dd9a45328b7284efd"
  UTILS_SECRET: "6f7aaea86de00f6f794b1d3c1324d9aad6ff1546b89220cb8535428a537ded96"
  DEFAULT_LANGUAGE: "en_US"
  FORCE_HTTPS: "false"
  URL: "http://outline.local"

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

persistence:
  enabled: true
  size: 1Gi