replicaCount: 1

image:
  repository: mysql
  tag: 8.4.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

rootPassword: MysqlAdmin2026!
database: ""

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m