replicaCount: 1

image:
  repository: mysql
  tag: 8.4.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

rootPassword: MysqlAdmin2026!
database: ""

config:
  characterSetServer: utf8mb4
  collationServer: utf8mb4_unicode_ci
  maxConnections: 100
  connectTimeout: 10
  waitTimeout: 28800
  maxAllowedPacket: 64M
  sortBufferSize: 4M
  joinBufferSize: 4M
  threadCacheSize: 8
  innodb:
    bufferPoolSize: 512M
    logFileSize: 128M
    flushLogAtTrxCommit: 1
    flushMethod: O_DIRECT
    ioCapacity: 200
    readIoThreads: 4
    writeIoThreads: 4
    lockWaitTimeout: 50
    logBufferSize: 16M
    changeBuffering: all
    autoincLockMode: 2
    tempDataFileMaxSize: 256M

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m