apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "it-tools.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "it-tools.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "it-tools.name" . }}
    spec:
      containers:
        - name: it-tools
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}