apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rabbitmq.name" . }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.user }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.password }}"
            - name: RABBITMQ_ERLANG_COOKIE
              value: secret-cookie-for-cluster
          command:
            - sh
            - -c
            - |
              cat > /etc/rabbitmq/rabbitmq.conf << 'RMQEOF'
              default_user = {{ .Values.user }}
              default_pass = {{ .Values.password }}
              vm_memory_high_watermark.relative = {{ .Values.config.vmMemoryHighWatermark }}
              vm_memory_high_watermark_paging_ratio = {{ .Values.config.vmMemoryHighWatermarkPagingRatio }}
              heartbeat = {{ .Values.config.heartbeat }}
              max_message_size = {{ .Values.config.maxMessageSize }}
              default_queue_type = {{ .Values.config.defaultQueueType }}
              channel_max = {{ .Values.config.channelMax }}
              connection_max = {{ .Values.config.connectionMax }}
              frame_max = {{ .Values.config.frameMax }}
              tcp_listen_options.backlog = {{ .Values.config.tcpListenOptions.backlog }}
              tcp_listen_options.nodelay = {{ .Values.config.tcpListenOptions.nodelay }}
              management.path_prefix = {{ .Values.config.managementPathPrefix }}
              collect_statistics = {{ .Values.config.collectStatistics }}
              log.level = {{ .Values.config.logLevel }}
              disk_free_limit.absolute = {{ .Values.config.diskFreeLimit }}
              RMQEOF
              rabbitmq-server
          resources:
            {{- toYaml .Values.resources | nindent 12 }}