{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.password }}
    - secretKey: erlang-cookie
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.erlangCookie }}
{{- end }}
