{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  password: {{ .Values.password | quote }}
  erlang-cookie: {{ .Values.erlangCookie | default "rabbitmq-cluster-cookie" | quote }}
{{- end }}
