apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  ports:
    - name: amqp
      port: {{ .Values.service.ports.amqp }}
      targetPort: 5672
    - name: management
      port: {{ .Values.service.ports.management }}
      targetPort: 15672
  selector:
    app: {{ include "rabbitmq.name" . }}