{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: minio-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.accessKey }}
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.secretKey }}
{{- end }}
