{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  access-key: {{ .Values.accessKey | quote }}
  secret-key: {{ .Values.secretKey | quote }}
{{- end }}
