apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.ports.console }}
      targetPort: 9001
  selector:
    app: {{ include "minio.name" . }}