apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "valkey.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "valkey.name" . }}
    spec:
      containers:
        - name: valkey
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.resources | nindent 12 }}