apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ include "valkey.name" . }}