replicaCount: 1

image:
  repository: valkey/valkey
  tag: 7.2.8-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

config:
  maxmemory: 128mb
  maxmemoryPolicy: allkeys-lru
  maxclients: 200
  timeout: 300
  tcpKeepalive: 60
  databases: 16
  save: "900 1 300 10 60 10000"
  appendonly: yes
  appendfsync: everysec
  noAppendfsyncOnRewrite: yes
  autoAofRewritePercentage: 100
  autoAofRewriteMinSize: 64mb
  slowlogLogSlowerThan: 10000
  slowlogMaxLen: 128
  activedefrag: yes
  activeDefragThresholdLower: 10
  activeDefragThresholdUpper: 100
  activeDefragCycleMin: 1
  activeDefragCycleMax: 25
  lazyfreeLazyEviction: yes
  lazyfreeLazyExpire: yes
  lazyfreeLazyServerDel: yes
  ioThreadsDoReads: no
  ioThreads: 1

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m