{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: outline-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.secretKey }}
    - secretKey: utils_secret
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.utilsSecret }}
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.dbPassword }}
    - secretKey: minio-secretkey
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.minioSecretKey }}
{{- end }}
