{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: master_key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.masterKey }}
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.dbPassword }}
{{- end }}
