replicaCount: 1

image:
  repository: mongo
  tag: 8.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

rootUser: root
rootPassword: MongoAdmin2026!
initDatabase: admin

config:
  wiredTigerCacheSizeGb: 0.5
  wiredTigerMaxCacheOverflow: 1
  maxConnections: 100
  operationProfilingMode: 1
  slowOpThresholdMs: 200
  logLevel: 0
  setParameter:
    internalQueryExecMaxBlockingSortBytes: 33554432
    internalQueryMaxHashMemory: 52428800
    internalQueryMaxRangeBlockingLimit: 10000
    internalQueryFrameworkControl: ""
    transactionLifetimeLimitSeconds: 60
    maxTransactionLockRequestTimeoutMillis: 5

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m