replicaCount: 1

image:
  repository: mongo
  tag: 8.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

rootUser: root
rootPassword: MongoAdmin2026!
initDatabase: admin

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 1000m