replicaCount: 1

image:
  repository: look0608/devops-admin-user
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: docker-hub

service:
  type: ClusterIP
  port: 8084

timezone: Asia/Shanghai

javaOpts: "-Xms256m -Xmx512m"

nacos:
  addr: "nacos.middleware:8848"
  namespace: ""
  group: "DEFAULT_GROUP"

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 500m
