apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nacos.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nacos.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nacos.name" . }}
    spec:
      containers:
        - name: nacos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8848
            - containerPort: 9848
            - containerPort: 9849
          env:
            - name: MODE
              value: "{{ .Values.mode }}"
            - name: MYSQL_SERVICE_HOST
              value: "{{ .Values.db.host }}"
            - name: MYSQL_SERVICE_PORT
              value: "{{ .Values.db.port }}"
            - name: MYSQL_SERVICE_DB_NAME
              value: "{{ .Values.db.name }}"
            - name: MYSQL_SERVICE_USER
              value: "{{ .Values.db.user }}"
            - name: MYSQL_SERVICE_PASSWORD
              value: "{{ .Values.db.password }}"
            - name: MYSQL_SERVICE_DB_PARAM
              value: "{{ .Values.db.params }}"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_AUTH_ENABLE
              value: "true"
            - name: NACOS_AUTH_TOKEN
              value: "{{ .Values.auth.token }}"
            - name: NACOS_AUTH_IDENTITY_KEY
              value: "{{ .Values.auth.identityKey }}"
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: "{{ .Values.auth.identityValue }}"
            - name: NACOS_AUTH_TOKEN_EXPIRE_SECONDS
              value: "{{ .Values.auth.tokenExpireSeconds }}"
            - name: NACOS_AUTH_CACHE_ENABLE
              value: "{{ .Values.auth.cacheEnabled }}"
            - name: JVM_XMS
              value: "{{ .Values.jvm.xms }}"
            - name: JVM_XMX
              value: "{{ .Values.jvm.xmx }}"
            - name: JVM_XMN
              value: "{{ .Values.jvm.xmn }}"
            - name: JVM_MS
              value: "{{ .Values.jvm.metaspace }}"
            - name: JVM_MMS
              value: "{{ .Values.jvm.maxMetaspace }}"
            - name: MYSQL_SERVICE_DB_NUM
              value: "1"
            - name: DB_POOL_CONNECTION_TIMEOUT
              value: "{{ .Values.db.pool.connectionTimeout }}"
            - name: DB_POOL_MAX_LIFETIME
              value: "{{ .Values.db.pool.maxLifetime }}"
            - name: DB_POOL_VALIDATION_TIMEOUT
              value: "{{ .Values.db.pool.validationTimeout }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}