{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nacos-secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.store.name }}
    kind: {{ .Values.externalSecret.store.kind }}
  target:
    name: nacos-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.dbPassword }}
    - secretKey: auth-token
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.authToken }}
    - secretKey: auth-identity-key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.authIdentityKey }}
    - secretKey: auth-identity-value
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.authIdentityValue }}
{{- end }}
