{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nacos-secret
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  auth-token: {{ .Values.auth.token | quote }}
  auth-identity-key: {{ .Values.auth.identityKey | quote }}
  auth-identity-value: {{ .Values.auth.identityValue | quote }}
{{- end }}
